spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/microdiag-app/protocol/openid-connect/certs
  application:
    name: risk-ms
eureka:
  instance:
    lease-renewal-interval-in-seconds: '10'
    lease-expiration-duration-in-seconds: '30'
  client:
    serviceUrl:
      defaultZone: http://localhost:${eurekaMSPort}/eureka/
server:
  port: ${riskMSport}

# environment variables
eurekaMSPort: '9102'
riskMSport: '9006'
gatewayMSPort: '9004'
